[dependencies]
num-traits = '0.2.6'
criterion = "0.2.9"

[dev-dependencies]
criterion = "0.2.9"

[[bench]]
name = "bench"
harness = false

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'adaptrapezoid'
version = '0.1.0'
